version: '2'

services:
  db:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_DB=headspace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'

  search:
    image: elasticsearch:6.4.0
    ports:
      - '127.0.0.1:9200:9200'
  
  web:
    image: headspace:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    container_name: headspace_container
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=rtt4leia4_rbe(t)h1k1o#8jgl-*nyc60fh3nto0zr**hmq=o@
      - DOCKER_CONTAINER=True
    depends_on:
      - db
      - redis
      - search