version: '3'

services:
  db:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  search:
    image: elasticsearch:6.4.0
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - search